#define SPRITE_BLANK            0x00 /*   */
#define SPRITE_FACE_EMPTY       0x01 /* ☺ */
#define SPRITE_FACE_FILL        0x02 /* ☻ */
#define SPRITE_HEART            0x03 /* ♥ */
#define SPRITE_DIAMOND          0x04 /* ♦ */
#define SPRITE_CLUB             0x05 /* ♣ */
#define SPRITE_SPADE            0x06 /* ♠ */
#define SPRITE_OVAL             0x07 /* • */
#define SPRITE_OVAL_R           0x08 /* ◘ */
#define SPRITE_CIRCLE           0x09 /* ○ */
#define SPRITE_CIRCLE_R         0x0a /* ◙ */
#define SPRITE_MARS             0x0b /* ♂ */
#define SPRITE_VENUS            0x0c /* ♀ */
#define SPRITE_NOTE             0x0d /* ♪ */
#define SPRITE_NOTE_DOUBLE      0x0e /* ♫ */
#define SPRITE_SUN              0x0f /* ☼ */

#define SPRITE_TRI_RIGHT        0x10 /* ► */
#define SPRITE_TRI_LEFT         0x11 /* ◄ */
#define SPRITE_ARROW_UD         0x12 /* ↕ */
#define SPRITE_EXC_DOUBLE       0x13 /* ‼ */
#define SPRITE_PARA             0x14 /* ¶ */
#define SPRITE_SIMOLEON         0x15 /* § */
#define SPRITE_RECTANGLE        0x16 /* ▬ */
#define SPRITE_ARROW_UD_US      0x17 /* ↨ */
#define SPRITE_ARROW_U          0x18 /* ↑ */
#define SPRITE_ARROW_D          0x19 /* ↓ */
#define SPRITE_ARROW_R          0x1a /* → */
#define SPRITE_ARROW_L          0x1b /* ← */
#define SPRITE_RIGHT_ANGLE      0x1c /* ∟ */
#define SPRITE_ARROW_LR         0x1d /* ↔ */
#define SPRITE_TRI_UP           0x1e /* ▲ */
#define SPRITE_TRI_DOWN         0x1f /* ▼ */

#define SPRITE_BLANK_2          0x20 /*   */
#define SPRITE_EXC              0x21 /* ! */
#define SPRITE_QUOTE            0x22 /* " */
#define SPRITE_HASH             0x23 /* # */
#define SPRITE_DOLLAR           0x24 /* $ */
#define SPRITE_PERCENT          0x25 /* % */
#define SPRITE_AMPERSAND        0x26 /* & */
#define SPRITE_APOSTROPHE       0x27 /* ' */
#define SPRITE_PAREN_L          0x28 /* ( */
#define SPRITE_PAREN_R          0x29 /* ) */
#define SPRITE_ASTERISK         0x2a /* * */
#define SPRITE_PLUS             0x2b /* + */
#define SPRITE_COMMA            0x2c /* , */
#define SPRITE_DASH             0x2d /* - */
#define SPRITE_PERIOD           0x2e /* . */
#define SPRITE_SLASH            0x2f /* / */

#define SPRITE_ZERO             0x30 /* 0 */
#define SPRITE_ONE              0x31 /* 1 */
#define SPRITE_TWO              0x32 /* 2 */
#define SPRITE_THREE            0x33 /* 3 */
#define SPRITE_FOUR             0x34 /* 4 */
#define SPRITE_FIVE             0x35 /* 5 */
#define SPRITE_SIX              0x36 /* 6 */
#define SPRITE_SEVEN            0x37 /* 7 */
#define SPRITE_EIGHT            0x38 /* 8 */
#define SPRITE_NINE             0x39 /* 9 */
#define SPRITE_COLON            0x3a /* : */
#define SPRITE_SEMICOLON        0x3b /* ; */
#define SPRITE_ANGLE_L          0x3c /* < */
#define SPRITE_EQUALS           0x3c /* = */
#define SPRITE_ANGLE_R          0x3e /* > */
#define SPRITE_QUESTION         0x3f /* ? */

#define SPRITE_AT               0x40 /* @ */
#define SPRITE_A_CAP            0x41 /* A */
#define SPRITE_B_CAP            0x42 /* B */
#define SPRITE_C_CAP            0x43 /* C */
#define SPRITE_D_CAP            0x44 /* D */
#define SPRITE_E_CAP            0x45 /* E */
#define SPRITE_F_CAP            0x46 /* F */
#define SPRITE_G_CAP            0x47 /* G */
#define SPRITE_H_CAP            0x48 /* H */
#define SPRITE_I_CAP            0x49 /* I */
#define SPRITE_J_CAP            0x4a /* J */
#define SPRITE_K_CAP            0x4b /* K */
#define SPRITE_L_CAP            0x4c /* L */
#define SPRITE_M_CAP            0x4d /* M */
#define SPRITE_N_CAP            0x4e /* N */
#define SPRITE_O_CAP            0x4f /* O */

#define SPRITE_P_CAP            0x50 /* P */
#define SPRITE_Q_CAP            0x51 /* Q */
#define SPRITE_R_CAP            0x52 /* R */
#define SPRITE_S_CAP            0x53 /* S */
#define SPRITE_T_CAP            0x54 /* T */
#define SPRITE_U_CAP            0x55 /* U */
#define SPRITE_V_CAP            0x56 /* V */
#define SPRITE_W_CAP            0x57 /* W */
#define SPRITE_X_CAP            0x58 /* X */
#define SPRITE_Y_CAP            0x59 /* Y */
#define SPRITE_Z_CAP            0x5a /* Z */
#define SPRITE_SQUARE_L         0x5b /* [ */
#define SPRITE_BACKSLASH        0x5c /* \ */
#define SPRITE_SQUARE_R         0x5d /* ] */
#define SPRITE_CARET            0x5e /* ^ */
#define SPRITE_UNDERSCORE       0x5f /* _ */

#define SPRITE_BACKTICK         0x60 /* ` */
#define SPRITE_A                0x61 /* a */
#define SPRITE_B                0x62 /* b */
#define SPRITE_C                0x63 /* c */
#define SPRITE_D                0x64 /* d */
#define SPRITE_E                0x65 /* e */
#define SPRITE_F                0x66 /* f */
#define SPRITE_G                0x67 /* g */
#define SPRITE_H                0x68 /* h */
#define SPRITE_I                0x69 /* i */
#define SPRITE_J                0x6a /* j */
#define SPRITE_K                0x6b /* k */
#define SPRITE_L                0x6c /* l */
#define SPRITE_M                0x6d /* m */
#define SPRITE_N                0x6e /* n */
#define SPRITE_O                0x6f /* o */

#define SPRITE_P                0x70 /* p */
#define SPRITE_Q                0x71 /* q */
#define SPRITE_R                0x72 /* r */
#define SPRITE_S                0x73 /* s */
#define SPRITE_T                0x74 /* t */
#define SPRITE_U                0x75 /* u */
#define SPRITE_V                0x76 /* v */
#define SPRITE_W                0x77 /* w */
#define SPRITE_X                0x78 /* x */
#define SPRITE_Y                0x79 /* y */
#define SPRITE_Z                0x7a /* z */
#define SPRITE_CURLY_L          0x7b /* { */
#define SPRITE_BROKEN_PIPE      0x7c /* | */
#define SPRITE_CURLY_R          0x7d /* } */
#define SPRITE_TILDE            0x7e /* ~ */
#define SPRITE_HOUSE            0x7f /* ⌂ */

#define SPRITE_C_CEDILLA_CAP    0x80 /* Ç */
#define SPRITE_U_UMLAUT         0x81 /* ü */
#define SPRITE_E_ACUTE          0x82 /* é */
#define SPRITE_A_CIRCUM         0x83 /* â */
#define SPRITE_A_UMLAUT         0x84 /* ä */
#define SPRITE_A_GRAVE          0x85 /* à */
#define SPRITE_A_RING           0x86 /* å */
#define SPRITE_C_CEDILLA        0x87 /* ç */
#define SPRITE_E_CIRCUM         0x88 /* ê */
#define SPRITE_E_UMLAUT         0x89 /* ë */
#define SPRITE_E_GRAVE          0x8a /* è */
#define SPRITE_I_UMLAUT         0x8b /* ï */
#define SPRITE_I_CIRCUM         0x8c /* î */
#define SPRITE_I_GRAVE          0x8d /* ì */
#define SPRITE_A_UMLAUT_CAP     0x8e /* Ä */
#define SPRITE_A_RING_CAP       0x8f /* Å */

#define SPRITE_E_ACUTE_CAP      0x90 /* É */
#define SPRITE_ASH              0x91 /* æ */
#define SPRITE_ASH_CAP          0x92 /* Æ */
#define SPRITE_O_CIRCUM         0x93 /* ô */
#define SPRITE_O_UMLAUT         0x94 /* ö */
#define SPRITE_O_GRAVE          0x95 /* ò */
#define SPRITE_U_CIRCUM         0x96 /* û */
#define SPRITE_U_GRAVE          0x97 /* ù */
#define SPRITE_Y_UMLAUT         0x98 /* ÿ */
#define SPRITE_O_UMLAUT_CAP     0x99 /* Ö */
#define SPRITE_U_UMLAUT_CAP     0x9a /* Ü */
#define SPRITE_CENT             0x9b /* ¢ */
#define SPRITE_POUND            0x9c /* £ */
#define SPRITE_YEN              0x9d /* ¥ */
#define SPRITE_PESETA           0x9e /* ₧ */
#define SPRITE_FRANC            0x9f /* ƒ */

#define SPRITE_A_ACUTE          0xa0 /* á */
#define SPRITE_I_ACUTE          0xa1 /* í */
#define SPRITE_O_ACUTE          0xa2 /* ó */
#define SPRITE_U_ACUTE          0xa3 /* ú */
#define SPRITE_N_TILDE          0xa4 /* ñ */
#define SPRITE_N_TILDE_CAP      0xa5 /* Ñ */
#define SPRITE_A_ORDINAL        0xa6 /* ª */
#define SPRITE_O_ORDINAL        0xa7 /* º */
#define SPRITE_QUESTION_REV     0xa8 /* ¿ */
#define SPRITE_NOT_REV          0xa9 /* ⌐ */
#define SPRITE_NOT              0xaa /* ¬ */
#define SPRITE_HALF             0xab /* ½ */
#define SPRITE_QUARTER          0xac /* ¼ */
#define SPRITE_EXC_REV          0xad /* ¡ */
#define SPRITE_DOUBLE_ANGLE_L   0xae /* « */
#define SPRITE_DOUBLE_ANGLE_R   0xaf /* » */

#define SPRITE_LIGHT_SHADE      0xb0 /* ░ */
#define SPRITE_MEDIUM_SHADE     0xb1 /* ▒ */
#define SPRITE_DARK_SHADE       0xb2 /* ▓ */
#define SPRITE_BOX_LIGHT_V      0xb3 /* │ */
#define SPRITE_BOX_LIGHT_V_L    0xb4 /* ┤ */
#define SPRITE_BOX_LIGHT_V_LL   0xb5 /* ╡ */
#define SPRITE_BOX_LIGHT_VV_L   0xb6 /* ╢ */
#define SPRITE_BOX_LIGHT_DD_L   0xb7 /* ╖ */
#define SPRITE_BOX_LIGHT_D_LL   0xb8 /* ╕ */
#define SPRITE_BOX_LIGHT_VV_LL  0xb9 /* ╣ */
#define SPRITE_BOX_LIGHT_VV     0xba /* ║ */
#define SPRITE_BOX_LIGHT_DD_LL  0xbb /* ╗ */
#define SPRITE_BOX_LIGHT_UU_LL  0xbc /* ╝ */
#define SPRITE_BOX_LIGHT_UU_L   0xbd /* ╜ */
#define SPRITE_BOX_LIGHT_U_LL   0xbe /* ╛ */
#define SPRITE_BOX_LIGHT_D_L    0xbf /* ┐ */

#define SPRITE_BOX_LIGHT_U_R    0xc0 /* └ */
#define SPRITE_BOX_LIGHT_U_H    0xc1 /* ┴ */
#define SPRITE_BOX_LIGHT_D_H    0xc2 /* ┬ */
#define SPRITE_BOX_LIGHT_V_R    0xc3 /* ├ */
#define SPRITE_BOX_LIGHT_H      0xc4 /* ─ */
#define SPRITE_BOX_LIGHT_V_H    0xc5 /* ┼ */
#define SPRITE_BOX_LIGHT_V_RR   0xc6 /* ╞ */
#define SPRITE_BOX_LIGHT_VV_R   0xc7 /* ╟ */
#define SPRITE_BOX_LIGHT_UU_RR  0xc8 /* ╚ */
#define SPRITE_BOX_LIGHT_DD_RR  0xc9 /* ╔ */
#define SPRITE_BOX_LIGHT_UU_HH  0xca /* ╩ */
#define SPRITE_BOX_LIGHT_DD_HH  0xcb /* ╦ */
#define SPRITE_BOX_LIGHT_VV_RR  0xcc /* ╠ */
#define SPRITE_BOX_LIGHT_HH     0xcd /* ═ */
#define SPRITE_BOX_LIGHT_VV_HH  0xce /* ╬ */
#define SPRITE_BOX_LIGHT_U_HH   0xcf /* ╧ */

#define SPRITE_BOX_LIGHT_UU_H   0xd0 /* ╨ */
#define SPRITE_BOX_LIGHT_D_HH   0xd1 /* ╤ */
#define SPRITE_BOX_LIGHT_DD_H   0xd2 /* ╥ */
#define SPRITE_BOX_LIGHT_UU_R   0xd3 /* ╙ */
#define SPRITE_BOX_LIGHT_U_RR   0xd4 /* ╘ */
#define SPRITE_BOX_LIGHT_D_RR   0xd5 /* ╒ */
#define SPRITE_BOX_LIGHT_DD_R   0xd6 /* ╓ */
#define SPRITE_BOX_LIGHT_VV_H   0xd7 /* ╫ */
#define SPRITE_BOX_LIGHT_V_HH   0xd8 /* ╪ */
#define SPRITE_BOX_LIGHT_U_L    0xd9 /* ┘ */
#define SPRITE_BOX_LIGHT_D_R    0xda /* ┌ */
#define SPRITE_FULL_BLOCK       0xdb /* █ */
#define SPRITE_LOWER_HALF_BLOCK 0xdc /* ▄ */
#define SPRITE_LEFT_HALF_BLOCK  0xdd /* ▌ */
#define SPRITE_RIGHT_HALF_BLOCK 0xde /* ▐ */
#define SPRITE_UPPER_HALF_BLOCK 0xdf /* ▀ */

#define SPRITE_ALPHA            0xe0 /* α */
#define SPRITE_BETA             0xe1 /* ß */
#define SPRITE_GAMMA            0xe2 /* Γ */
#define SPRITE_PI               0xe3 /* π */
#define SPRITE_SIGMA_CAP        0xe4 /* Σ */
#define SPRITE_SIGMA            0xe5 /* σ */
#define SPRITE_MU               0xe6 /* µ */
#define SPRITE_TAU              0xe7 /* τ */
#define SPRITE_PHI_CAP          0xe8 /* Φ */
#define SPRITE_THETA            0xe9 /* Θ */
#define SPRITE_OMEGA            0xea /* Ω */
#define SPRITE_DELTA            0xeb /* δ */
#define SPRITE_INFINITY         0xec /* ∞ */
#define SPRITE_PHI              0xed /* ϕ */
#define SPRITE_EPSILON          0xee /* ε */
#define SPRITE_INTERSECTION     0xef /* ∩ */

#define SPRITE_TRIPLE_BAR       0xf0 /* ≡ */
#define SPRITE_PLUS_MINUS       0xf1 /* ± */
#define SPRITE_GREATER_EQUAL    0xf2 /* ≥ */
#define SPRITE_LESS_EQUAL       0xf3 /* ≤ */
#define SPRITE_INTEGRAL_UPPER   0xf4 /* ⌠ */
#define SPRITE_INTEGRAL_LOWER   0xf5 /* ⌡ */
#define SPRITE_DIVIDE           0xf6 /* ÷ */
#define SPRITE_APPROX           0xf7 /* ≈ */
#define SPRITE_DEGREE           0xf8 /* ° */
#define SPRITE_BULLET           0xf9 /* ∙ */
#define SPRITE_INTERPUNCT       0xfa /* · */
#define SPRITE_ROOT             0xfb /* √ */
#define SPRITE_N_EXPONENT       0xfc /* ⁿ */
#define SPRITE_SQUARED          0xfd /* ² */
#define SPRITE_SQUARE           0xfe /* ■ */
#define SPRITE_BLANK_3          0xff /*   */
